spring:
  application:
    name: Expense-Tracker
  datasource:
    url: jdbc:mysql://localhost:3306/expense_tracker
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8081
  shutdown: graceful