spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expense_tracker
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: "classpath:changelog/db.changelog-dev.xml"
    enabled: true
application:
  jwt:
    expiration-millis: 604800000   # 7 days in millisecond
    secret: ${JWT_SECRET_KEY}
server:
  port: 8081
  shutdown: graceful

springdoc:
  swagger-ui:
    path: /ui
  title: Expense Tracker API
  version: '@springdoc-openapi-starter-webmvc-ui.version@' #read the value from pom.xml
openapi:
    output:
      file: 'openapi-@project.name@.json'
